Update README and add design document
wpi-acm/Hack-WPI pull request #2
Opened 2017-11-21 05:18 UTC by byliuyang

2017-11-21 16:28 UTC, binamkayastha requested changes
Nice work! Thanks for the great design! See comments below.

2017-11-21 16:28 UTC, binamkayastha commented on design/README.md
> +## Contributing
Should this be in the top level readme?

2017-11-21 16:28 UTC, binamkayastha commented on design/README.md
> +4. You may merge the Pull Request in once you have the sign-off of two other developers, or if you do not have permission to do that, you may request the second reviewer to merge it for you.
Lol we don't have enough developers to have two reviewers. You can probably just remove the whole number

2017-11-21 16:28 UTC, binamkayastha commented on design/README.md
> +This design document is licensed under the Creative Commons 4.0 - see the [LICENSE.md](LICENSE.md) file for details
Please change to GPL 2

2017-11-22 01:55 UTC, binamkayastha commented on design/README.md
> +4. You may merge the Pull Request in once you have the sign-off of two other developers, or if you do not have permission to do that, you may request the second reviewer to merge it for you.
Talked this over with Harry, this is specifically for design documents, so both Harry and I can review them.

2017-11-22 01:55 UTC, binamkayastha commented on design/README.md
> +## Contributing
Talked this over with Harry, this secion is specifically for the design documents.

2018-05-18 17:35 UTC, binamkayastha commented
Out of curiosity, did you ever implement the design document?

2018-05-26 14:23 UTC, naturetime10 commented
Yes, I did.

2018-10-24 07:50 UTC, closed without merging